export const  REQUEST_CITIES = 'REQUEST_CITIES';
export const  RECEIVE_CITIES = 'REQUEST_CITIES';
export const  FAILURE_FETCHING_CITIES = 'REQUEST_CITIES';
export const  FILTER_CITIES = 'FILTER_CITIES';
export const  CLEAR_CITIES = 'CLEAR_CITIES';